app = 'register-queue'
primary_region = 'arn'

[build]

[env]
  PORT = '8000'
  DENO_KV_SQLITE_PATH = "/data/denokv.sqlite3"

[processes]
  app = 'serve -A --unstable-kv ./src/main.ts'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  destination = "/data"
  source = "denokv_data"
