# fly.toml app configuration file generated for register-queue on 2024-09-01T14:41:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'register-queue'
primary_region = 'arn'

[build]

[env]
  PORT = '8080'

[processes]
  app = 'run --allow-net ./example.ts'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
